apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: globex
  name: catalog-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-sc
